services:
  shopenapi:
    container_name: shopenapi
    build: .
    ports:
      - "${PORT}:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_DB_PASSWORD}
      PORT: ${PORT}

    depends_on:
      - shopendb
    networks:
      - shopen_network
    restart: unless-stopped

  shopendb:
    container_name: shopendb
    image: postgres:latest
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_DB_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_DB_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_DB_NAME}
      PGDATA: /data/postgres
    ports:
      - "${SPRING_DATASOURCE_DB_PORT}:5432"
    networks:
      - shopen_network
    restart: unless-stopped

networks:
  shopen_network:
    driver: bridge

volumes:
  shopendb_data:
